import os
base = r"c:\ideaProject\demo1\miniprogram"

def W(rel, s):
    p = os.path.join(base, rel)
    os.makedirs(os.path.dirname(p), exist_ok=True)
    with open(p, 'w', encoding='utf-8') as f:
        f.write(s.strip() + '\n')
    print('  ' + rel)

WXS = '\n<wxs module="img" src="../../utils/image.wxs" />\n'

# order-detail
W("pages/order-detail/order-detail.js", """var api=require('../../utils/api');Page({data:{order:null,items:[]},onLoad:function(opts){var t=this,id=parseInt(opts.id);api.getOrderDetail(id).then(function(r){var o=r.data||{};o.statusLabel=['待支付','已支付','已发货','已完成','已取消','退款中','已退款'][o.status||0]||'未知';t.setData({order:o,items:o.orderItems||[]});}).catch(function(){});},payOrder:function(){wx.navigateTo({url:'/pages/checkout/checkout?orderId='+this.data.order.id+'&mode=pay'});},cancel:function(){var t=this,oid=this.data.order.id;wx.showModal({title:'取消订单',success:function(r){if(r.confirm)api.cancelOrder(oid).then(function(){wx.navigateBack();});}});},confirmRecv:function(){var t=this,oid=this.data.order.id;wx.showModal({title:'确认收货',success:function(r){if(r.confirm)api.confirmReceive(oid).then(function(){wx.navigateBack();});}});},goRefund:function(){var t=this,oid=this.data.order.id;wx.showModal({title:'申请退款',success:function(r){if(r.confirm)api.applyRefund(oid).then(function(){wx.navigateBack();});}});},goLogistics:function(){wx.navigateTo({url:'/pages/logistics/logistics?orderId='+this.data.order.id});}});""")
W("pages/order-detail/order-detail.wxml", WXS+"""<view wx:if="{{!order}}" class="empty-state"><text>加载中...</text></view><block wx:if="{{order}}"><view style="background:#fff;padding:30rpx;margin-bottom:20rpx;"><view style="display:flex;justify-content:space-between;align-items:center;margin-bottom:16rpx;"><text style="font-size:32rpx;font-weight:bold;">订单详情</text><text class="status-tag status-{{order.status}}">{{order.statusLabel}}</text></view><view style="font-size:26rpx;color:#999;">订单号：{{order.orderNo}}</view><view style="font-size:26rpx;color:#999;">创建时间：{{order.createdTime}}</view></view><view class="card" wx:for="{{items}}" wx:key="id"><view style="display:flex;gap:20rpx;align-items:center;"><image src="{{img.img(item.productImage)}}" mode="aspectFill" style="width:140rpx;height:140rpx;border-radius:8rpx;background:#f0f0f0;"/><view style="flex:1;"><view style="font-size:28rpx;font-weight:600;">{{item.productName}}</view><view style="color:#999;font-size:24rpx;margin-top:8rpx;">x{{item.quantity}}</view><view style="color:#e74c3c;font-size:30rpx;font-weight:bold;margin-top:8rpx;">{{item.totalPrice||item.price}}</view></view></view></view><view class="card"><view style="font-size:28rpx;">收货人：{{order.receiverName}} {{order.receiverPhone}}</view><view style="font-size:26rpx;color:#999;margin-top:8rpx;">地址：{{order.shippingAddress}}</view><view wx:if="{{order.shippingCompany}}" style="font-size:26rpx;color:#999;margin-top:8rpx;">物流：{{order.shippingCompany}} {{order.trackingNumber}}</view><view style="display:flex;justify-content:space-between;margin-top:20rpx;padding-top:20rpx;border-top:1rpx solid #f0f0f0;"><text style="font-size:28rpx;">实付</text><text style="color:#e74c3c;font-size:36rpx;font-weight:bold;">{{order.actualAmount||order.totalAmount}}</text></view></view><view style="padding:30rpx;display:flex;flex-wrap:wrap;gap:16rpx;"><button wx:if="{{order.status===0}}" class="btn-primary" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="payOrder">立即支付</button><button wx:if="{{order.status===0}}" class="btn-ghost" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="cancel">取消订单</button><button wx:if="{{order.status===2}}" class="btn-primary" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="confirmRecv">确认收货</button><button wx:if="{{order.status===2}}" class="btn-ghost" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="goLogistics">查看物流</button><button wx:if="{{order.status>=1&&order.status<=3}}" class="btn-ghost" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="goRefund">申请退款</button></view></block>""")

# checkout
W("pages/checkout/checkout.js", """var api=require('../../utils/api');Page({data:{mode:'cart',orderId:null,cartItems:[],totalAmount:0,address:null,receiverName:'',receiverPhone:'',shippingAddress:'',remark:''},onLoad:function(opts){if(opts.orderId)this.setData({mode:'pay',orderId:parseInt(opts.orderId)});var t=this;if(this.data.mode==='cart'){api.getCart().then(function(r){var items=(r.data||[]).filter(function(i){return i.selected!==0;});var total=0;items.forEach(function(i){total+=(i.productPrice||0)*(i.quantity||1);});t.setData({cartItems:items,totalAmount:total.toFixed(2)});}).catch(function(){});}api.getDefaultAddr().then(function(r){var addr=r.data;if(addr)t.setData({address:addr,receiverName:addr.receiverName,receiverPhone:addr.receiverPhone,shippingAddress:addr.region+' '+addr.detailAddress});}).catch(function(){});},chooseAddr:function(){wx.navigateTo({url:'/pages/address/address?mode=select'});},onRemark:function(e){this.setData({remark:e.detail.value});},submitOrder:function(){var d=this.data;if(!d.shippingAddress){wx.showToast({title:'请选择地址',icon:'none'});return;}if(d.mode==='pay'){api.payOrder(d.orderId,'alipay').then(function(){wx.showToast({title:'支付成功',icon:'success'});setTimeout(function(){wx.switchTab({url:'/pages/order/order'});},1000);}).catch(function(e){wx.showToast({title:e.message||'支付失败',icon:'none'});});return;}var items=d.cartItems.map(function(i){return{productId:i.productId,productName:i.productName,productImage:i.productImage,price:i.productPrice,quantity:i.quantity};});var total=parseFloat(d.totalAmount);api.createOrder({totalAmount:total,actualAmount:total,shippingFee:0,discountAmount:0,shippingAddress:d.shippingAddress,receiverName:d.receiverName,receiverPhone:d.receiverPhone,remark:d.remark,items:items}).then(function(){wx.showToast({title:'下单成功',icon:'success'});setTimeout(function(){wx.switchTab({url:'/pages/order/order'});},1000);}).catch(function(e){wx.showToast({title:e.message||'下单失败',icon:'none'});});}});""")
W("pages/checkout/checkout.wxml", WXS+"""<view class="page-wrap"><view class="card" bindtap="chooseAddr"><view style="font-size:28rpx;font-weight:bold;margin-bottom:8rpx;">收货地址</view><view wx:if="{{address}}" style="font-size:26rpx;color:#333;">{{address.receiverName}} {{address.receiverPhone}}</view><view wx:if="{{address}}" style="font-size:24rpx;color:#999;margin-top:4rpx;">{{address.region}} {{address.detailAddress}}</view><view wx:if="{{!address}}" style="font-size:26rpx;color:#999;">请选择收货地址 ></view></view><view class="card" wx:for="{{cartItems}}" wx:key="productId"><view style="display:flex;gap:16rpx;align-items:center;"><image src="{{img.img(item.productImage)}}" mode="aspectFill" style="width:120rpx;height:120rpx;border-radius:8rpx;background:#f0f0f0;"/><view style="flex:1;"><view style="font-size:28rpx;">{{item.productName}}</view><view style="color:#999;font-size:24rpx;">x{{item.quantity}}</view></view><view style="color:#e74c3c;font-weight:bold;">{{((item.productPrice||0)*(item.quantity||1)).toFixed(2)}}</view></view></view><view class="card" wx:if="{{mode==='cart'}}"><view style="font-size:26rpx;color:#999;margin-bottom:8rpx;">备注</view><input placeholder="选填" value="{{remark}}" bindinput="onRemark" style="font-size:26rpx;"/></view><view style="position:fixed;bottom:0;left:0;right:0;background:#fff;padding:20rpx 30rpx;display:flex;align-items:center;justify-content:space-between;box-shadow:0 -2rpx 10rpx rgba(0,0,0,0.05);"><view><text style="font-size:24rpx;color:#999;">合计：</text><text style="color:#e74c3c;font-size:36rpx;font-weight:bold;">{{totalAmount}}</text></view><button class="btn-primary" style="width:200rpx;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="submitOrder">{{mode==='pay'?'确认支付':'提交订单'}}</button></view></view>""")

# address list
W("pages/address/address.js", """var api=require('../../utils/api');Page({data:{addresses:[],mode:'list'},onShow:function(){var t=this;api.getAddresses().then(function(r){t.setData({addresses:r.data||[]});}).catch(function(){});},onLoad:function(opts){if(opts.mode)this.setData({mode:opts.mode});},gotoEdit:function(e){var id=e?e.currentTarget.dataset.id:0;wx.navigateTo({url:'/pages/address-edit/address-edit?id='+(id||0)});},deleteAddr:function(e){var t=this,id=e.currentTarget.dataset.id;wx.showModal({title:'删除地址',success:function(r){if(r.confirm)api.deleteAddress(id).then(function(){t.onShow();});}});},selectAddr:function(e){if(this.data.mode!=='select')return;var pages=getCurrentPages(),prev=pages[pages.length-2];var addr=this.data.addresses[e.currentTarget.dataset.index];if(prev&&prev.setData)prev.setData({address:addr,receiverName:addr.receiverName,receiverPhone:addr.receiverPhone,shippingAddress:addr.region+' '+addr.detailAddress});wx.navigateBack();}});""")
W("pages/address/address.wxml", WXS+"""<view class="page-wrap"><view wx:if="{{addresses.length===0}}" class="empty-state"><text>暂无收货地址</text></view><view wx:for="{{addresses}}" wx:key="id" class="card" data-index="{{index}}" data-id="{{item.id}}" bindtap="{{mode==='select'?'selectAddr':''}}"><view style="display:flex;justify-content:space-between;align-items:center;margin-bottom:8rpx;"><text style="font-size:28rpx;font-weight:bold;">{{item.receiverName}} {{item.receiverPhone}}</text><text wx:if="{{item.isDefault}}" style="color:#667eea;font-size:22rpx;">默认</text></view><view style="font-size:26rpx;color:#666;">{{item.region}} {{item.detailAddress}}</view><view style="display:flex;gap:20rpx;margin-top:16rpx;justify-content:flex-end;"><text style="color:#667eea;font-size:24rpx;" data-id="{{item.id}}" catchtap="gotoEdit">编辑</text><text style="color:#ff6b6b;font-size:24rpx;" data-id="{{item.id}}" catchtap="deleteAddr">删除</text></view></view><button class="btn-primary" bindtap="gotoEdit" style="margin:30rpx 24rpx;">新增地址</button></view>""")

# address-edit
W("pages/address-edit/address-edit.js", """var api=require('../../utils/api');Page({data:{id:0,receiverName:'',receiverPhone:'',region:'',detailAddress:'',isDefault:0},onLoad:function(opts){if(opts.id&&opts.id!=='0')this.setData({id:parseInt(opts.id)});},onName:function(e){this.setData({receiverName:e.detail.value});},onPhone:function(e){this.setData({receiverPhone:e.detail.value});},onRegion:function(e){this.setData({region:e.detail.value});},onDetail:function(e){this.setData({detailAddress:e.detail.value});},setDefault:function(e){this.setData({isDefault:e.detail.value?1:0});},save:function(){var d=this.data;if(!d.receiverName||!d.receiverPhone||!d.region||!d.detailAddress){wx.showToast({title:'请填写完整',icon:'none'});return;}api.saveAddress({id:d.id||null,receiverName:d.receiverName,receiverPhone:d.receiverPhone,region:d.region,detailAddress:d.detailAddress,isDefault:d.isDefault}).then(function(){wx.showToast({title:'保存成功',icon:'success'});setTimeout(function(){wx.navigateBack();},1000);}).catch(function(e){wx.showToast({title:e.message||'保存失败',icon:'none'});});}});""")
W("pages/address-edit/address-edit.wxml", WXS+"""<view class="page-wrap" style="padding:30rpx;"><view style="background:#fff;border-radius:16rpx;padding:30rpx;"><input placeholder="收货人姓名" value="{{receiverName}}" bindinput="onName" style="height:80rpx;border-bottom:1rpx solid #f0f0f0;font-size:28rpx;"/><input placeholder="手机号" type="number" value="{{receiverPhone}}" bindinput="onPhone" style="height:80rpx;border-bottom:1rpx solid #f0f0f0;font-size:28rpx;"/><input placeholder="省市区" value="{{region}}" bindinput="onRegion" style="height:80rpx;border-bottom:1rpx solid #f0f0f0;font-size:28rpx;"/><input placeholder="详细地址" value="{{detailAddress}}" bindinput="onDetail" style="height:80rpx;border-bottom:1rpx solid #f0f0f0;font-size:28rpx;"/><view style="display:flex;align-items:center;margin-top:20rpx;"><switch checked="{{isDefault===1}}" bindchange="setDefault"/><text style="font-size:26rpx;margin-left:10rpx;">设为默认地址</text></view><button class="btn-primary" bindtap="save" style="margin-top:40rpx;">保存</button></view></view>""")

# favorites
W("pages/favorites/favorites.js", """var api=require('../../utils/api');Page({data:{items:[]},onShow:function(){var t=this;api.getFavorites().then(function(r){t.setData({items:r.data||[]});}).catch(function(){});},remove:function(e){var t=this,id=e.currentTarget.dataset.id;api.removeFav(id).then(function(){t.onShow();wx.showToast({title:'已取消',icon:'none'});});},goProduct:function(e){wx.navigateTo({url:'/pages/product-detail/product-detail?id='+e.currentTarget.dataset.id});}});""")
W("pages/favorites/favorites.wxml", WXS+"""<view class="page-wrap"><view wx:if="{{items.length===0}}" class="empty-state"><text>暂无收藏</text></view><view wx:for="{{items}}" wx:key="id" class="card" style="display:flex;gap:20rpx;align-items:center;"><image src="{{img.img(item.productImage)}}" mode="aspectFill" style="width:140rpx;height:140rpx;border-radius:8rpx;background:#f0f0f0;" data-id="{{item.productId}}" bindtap="goProduct"/><view style="flex:1;" data-id="{{item.productId}}" bindtap="goProduct"><view style="font-size:28rpx;font-weight:600;">{{item.productName}}</view><view style="color:#e74c3c;font-size:32rpx;font-weight:bold;margin-top:8rpx;">{{item.productPrice}}</view></view><view style="color:#ff6b6b;font-size:24rpx;" data-id="{{item.id}}" catchtap="remove">取消</view></view></view>""")

# coupons
W("pages/coupons/coupons.js", """var api=require('../../utils/api');Page({data:{coupons:[],myCoupons:[],tab:0},onShow:function(){var t=this;api.getAvailableCoupons().then(function(r){t.setData({coupons:r.data||[]});}).catch(function(){});api.myCoupons().then(function(r){t.setData({myCoupons:r.data||[]});}).catch(function(){});},switchTab:function(e){this.setData({tab:parseInt(e.currentTarget.dataset.tab)});},receive:function(e){var t=this,cid=e.currentTarget.dataset.id;api.receiveCoupon(cid).then(function(){wx.showToast({title:'领取成功',icon:'success'});t.onShow();}).catch(function(e){wx.showToast({title:e.message||'领取失败',icon:'none'});});}});""")
W("pages/coupons/coupons.wxml", WXS+"""<view class="page-wrap"><view style="display:flex;background:#fff;margin-bottom:20rpx;"><view data-tab="0" bindtap="switchTab" style="flex:1;text-align:center;padding:20rpx;font-size:28rpx;{{tab===0?'color:#667eea;border-bottom:3rpx solid #667eea;':''}}">可领取</view><view data-tab="1" bindtap="switchTab" style="flex:1;text-align:center;padding:20rpx;font-size:28rpx;{{tab===1?'color:#667eea;border-bottom:3rpx solid #667eea;':''}}">我的</view></view><block wx:if="{{tab===0}}"><view wx:if="{{coupons.length===0}}" class="empty-state"><text>暂无可领优惠券</text></view><view wx:for="{{coupons}}" wx:key="id" class="card" style="background:linear-gradient(135deg,#fff5f5,#fff8e1);"><view style="display:flex;justify-content:space-between;align-items:center;"><view><text style="font-size:48rpx;font-weight:bold;color:#e74c3c;">{{item.value}}{{item.type==='discount'?'折':'元'}}</text><text style="font-size:24rpx;color:#999;"> {{item.type==='discount'?'折扣券':'满减券'}}</text></view><button class="btn-primary" style="width:140rpx;height:60rpx;line-height:60rpx;font-size:24rpx;margin:0;" data-id="{{item.id}}" bindtap="receive">立即领取</button></view><view style="font-size:28rpx;font-weight:bold;margin-top:8rpx;">{{item.name}}</view><view style="font-size:24rpx;color:#999;margin-top:4rpx;">{{item.minAmount>0?'满'+item.minAmount+'元可用':'无门槛'}} | {{item.description}}</view></view></block><block wx:if="{{tab===1}}"><view wx:if="{{myCoupons.length===0}}" class="empty-state"><text>暂无优惠券</text></view><view wx:for="{{myCoupons}}" wx:key="id" class="card"><view style="font-size:32rpx;font-weight:bold;">{{item.couponValue}}{{item.couponType==='discount'?'折':'元'}} <text style="font-size:24rpx;color:#999;">{{item.couponType==='discount'?'折扣券':'满减券'}}</text></view><view style="font-size:26rpx;color:#666;margin-top:4rpx;">{{item.couponName}}</view><view style="font-size:24rpx;color:#999;margin-top:4rpx;">{{item.status===0?'可用':(item.status===1?'已使用':'已过期')}}</view></view></block></view>""")

# notifications
W("pages/notifications/notifications.js", """var api=require('../../utils/api');Page({data:{list:[],unreadCount:0},onShow:function(){var t=this;api.getNotifications(1,50).then(function(r){t.setData({list:r.data&&r.data.list||[],unreadCount:r.data&&r.data.unreadCount||0});}).catch(function(){});},markRead:function(e){var t=this,id=e.currentTarget.dataset.id;api.markRead(id).then(function(){t.onShow();});},markAll:function(){var t=this;api.markAllRead().then(function(){t.onShow();wx.showToast({title:'全部已读',icon:'none'});});}});""")
W("pages/notifications/notifications.wxml", WXS+"""<view class="page-wrap"><view wx:if="{{list.length>0}}" style="text-align:right;padding:16rpx 30rpx;"><text style="color:#667eea;font-size:24rpx;" bindtap="markAll">全部已读</text></view><view wx:if="{{list.length===0}}" class="empty-state"><text>暂无消息</text></view><view wx:for="{{list}}" wx:key="id" class="card" style="{{!item.isRead?'border-left:4rpx solid #667eea;':''}}"><view style="display:flex;justify-content:space-between;align-items:center;"><view style="font-size:28rpx;font-weight:{{item.isRead?400:700}};">{{item.title}}</view><view wx:if="{{!item.isRead}}" style="width:12rpx;height:12rpx;background:#ff6b6b;border-radius:50%;"></view></view><view style="font-size:24rpx;color:#999;margin-top:8rpx;line-height:1.6;">{{item.content}}</view><view style="display:flex;justify-content:space-between;margin-top:12rpx;"><text style="font-size:22rpx;color:#bbb;">{{item.createdTime}}</text><text wx:if="{{!item.isRead}}" style="color:#667eea;font-size:24rpx;" data-id="{{item.id}}" catchtap="markRead">标为已读</text></view></view></view>""")

# logistics
W("pages/logistics/logistics.js", """var api=require('../../utils/api');Page({data:{info:null},onLoad:function(opts){var t=this,oid=parseInt(opts.orderId);api.getLogistics(oid).then(function(r){t.setData({info:r.data||{}});}).catch(function(){});}});""")
W("pages/logistics/logistics.wxml", WXS+"""<view class="page-wrap"><view wx:if="{{!info}}" class="empty-state"><text>加载中...</text></view><block wx:if="{{info}}"><view class="card"><view style="font-size:28rpx;font-weight:bold;margin-bottom:12rpx;">物流信息</view><view style="font-size:26rpx;color:#666;">快递公司：{{info.shippingCompany||'暂无'}}</view><view style="font-size:26rpx;color:#666;margin-top:8rpx;">快递单号：{{info.trackingNumber||'暂无'}}</view><view style="font-size:26rpx;color:#666;margin-top:8rpx;">发货时间：{{info.deliveryTime||'暂无'}}</view></view><view class="card"><view style="font-size:28rpx;font-weight:bold;margin-bottom:12rpx;">收货信息</view><view style="font-size:26rpx;color:#666;">收货人：{{info.receiverName}}</view><view style="font-size:26rpx;color:#666;margin-top:8rpx;">地址：{{info.shippingAddress}}</view></view><view class="card"><view style="font-size:28rpx;font-weight:bold;margin-bottom:12rpx;">物流状态</view><view wx:if="{{info.status===2}}" style="font-size:26rpx;color:#1565c0;">运输中</view><view wx:if="{{info.status===3}}" style="font-size:26rpx;color:#2e7d32;">已签收</view><view wx:if="{{info.status<2}}" style="font-size:26rpx;color:#999;">等待发货</view></view></block></view>""")

# exchange
W("pages/exchange/exchange.js", """var api=require('../../utils/api');Page({data:{orders:[]},onShow:function(){var t=this;api.getExchangeList().then(function(r){var orders=(r.data||[]).map(function(o){o.statusLabel=['待确认','已确认','已完成','已取消','已拒绝'][o.status||0]||'未知';return o;});t.setData({orders:orders});}).catch(function(){});},goDetail:function(e){wx.navigateTo({url:'/pages/exchange-detail/exchange-detail?id='+e.currentTarget.dataset.id});}});""")
W("pages/exchange/exchange.wxml", WXS+"""<view class="page-wrap"><view wx:if="{{orders.length===0}}" class="empty-state"><text>暂无交换订单</text></view><view wx:for="{{orders}}" wx:key="id" class="card" data-id="{{item.id}}" bindtap="goDetail"><view style="display:flex;justify-content:space-between;margin-bottom:8rpx;"><text style="font-size:24rpx;color:#999;">{{item.orderNo}}</text><text class="status-tag status-{{item.status}}">{{item.statusLabel}}</text></view><view style="font-size:26rpx;color:#666;">差价：{{item.priceDifference||0}}元</view><view style="font-size:24rpx;color:#999;margin-top:4rpx;">{{item.createdTime}}</view></view></view>""")

# exchange-detail
W("pages/exchange-detail/exchange-detail.js", """var api=require('../../utils/api');Page({data:{order:null},onLoad:function(opts){var t=this;api.getExchangeList().then(function(r){var o=null;(r.data||[]).forEach(function(x){if(x.id===parseInt(opts.id))o=x;});if(o){o.statusLabel=['待确认','已确认','已完成','已取消','已拒绝'][o.status||0]||'未知';t.setData({order:o});}}).catch(function(){});},confirm:function(){var t=this,oid=this.data.order.id;api.confirmExchange(oid).then(function(){wx.showToast({title:'已确认',icon:'success'});t.onLoad({id:oid});});},reject:function(){var t=this,oid=this.data.order.id;api.rejectExchange(oid).then(function(){wx.showToast({title:'已拒绝',icon:'none'});t.onLoad({id:oid});});},cancel:function(){var t=this,oid=this.data.order.id;api.cancelExchange(oid).then(function(){wx.navigateBack();});}});""")
W("pages/exchange-detail/exchange-detail.wxml", WXS+"""<view class="page-wrap"><view wx:if="{{!order}}" class="empty-state"><text>加载中...</text></view><block wx:if="{{order}}"><view style="background:#fff;padding:30rpx;margin-bottom:20rpx;"><view style="display:flex;justify-content:space-between;align-items:center;"><text style="font-size:32rpx;font-weight:bold;">交换详情</text><text class="status-tag status-{{order.status}}">{{order.statusLabel}}</text></view><view style="font-size:24rpx;color:#999;margin-top:8rpx;">{{order.orderNo}}</view><view style="font-size:26rpx;color:#666;margin-top:8rpx;">差价：{{order.priceDifference||0}} 元</view></view><view style="padding:30rpx;display:flex;gap:16rpx;"><button wx:if="{{order.status===0}}" class="btn-primary" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="confirm">确认交换</button><button wx:if="{{order.status===0}}" class="btn-ghost" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="reject">拒绝</button><button wx:if="{{order.status===0||order.status===1}}" class="btn-ghost" style="flex:1;height:72rpx;line-height:72rpx;font-size:28rpx;margin:0;" bindtap="cancel">取消交换</button></view></block></view>""")

# refund
W("pages/refund/refund.js", """var api=require('../../utils/api');Page({data:{orderId:0,reason:''},onLoad:function(opts){if(opts.orderId)this.setData({orderId:parseInt(opts.orderId)});},onReason:function(e){this.setData({reason:e.detail.value});},submit:function(){var t=this;api.applyRefund(t.data.orderId).then(function(){wx.showToast({title:'退款已提交',icon:'success'});setTimeout(function(){wx.navigateBack();},1000);}).catch(function(e){wx.showToast({title:e.message||'提交失败',icon:'none'});});}});""")
W("pages/refund/refund.wxml", WXS+"""<view class="page-wrap" style="padding:30rpx;"><view style="background:#fff;border-radius:16rpx;padding:30rpx;"><view style="font-size:28rpx;font-weight:bold;margin-bottom:20rpx;">申请退款</view><textarea placeholder="请描述退款原因" value="{{reason}}" bindinput="onReason" style="width:100%;height:200rpx;border:1rpx solid #f0f0f0;border-radius:8rpx;padding:16rpx;font-size:26rpx;"/><button class="btn-primary" bindtap="submit" style="margin-top:30rpx;">提交申请</button></view></view>""")

# reviews
W("pages/reviews/reviews.js", """var api=require('../../utils/api');Page({data:{productId:0,rating:5,content:''},onLoad:function(opts){if(opts.productId)this.setData({productId:parseInt(opts.productId)});},setRating:function(e){this.setData({rating:parseInt(e.currentTarget.dataset.r)});},onContent:function(e){this.setData({content:e.detail.value});},submit:function(){var d=this.data;if(!d.content){wx.showToast({title:'请填写评价',icon:'none'});return;}api.submitReview(d.productId,{rating:d.rating,content:d.content}).then(function(){wx.showToast({title:'评价成功',icon:'success'});setTimeout(function(){wx.navigateBack();},1000);}).catch(function(e){wx.showToast({title:e.message||'评价失败',icon:'none'});});}});""")
W("pages/reviews/reviews.wxml", WXS+"""<view class="page-wrap" style="padding:30rpx;"><view style="background:#fff;border-radius:16rpx;padding:30rpx;"><view style="font-size:28rpx;font-weight:bold;margin-bottom:20rpx;">写评价</view><view style="display:flex;gap:12rpx;margin-bottom:20rpx;"><text wx:for="{{[1,2,3,4,5]}}" wx:key="*this" data-r="{{item}}" bindtap="setRating" style="font-size:44rpx;{{item<=rating?'color:#ffa502;':'color:#ddd;'}}">★</text></view><textarea placeholder="分享您的使用感受" value="{{content}}" bindinput="onContent" style="width:100%;height:200rpx;border:1rpx solid #f0f0f0;border-radius:8rpx;padding:16rpx;font-size:26rpx;"/><button class="btn-primary" bindtap="submit" style="margin-top:30rpx;">提交评价</button></view></view>""")

# feedback
W("pages/feedback/feedback.js", """var api=require('../../utils/api');Page({data:{content:'',contact:''},onContent:function(e){this.setData({content:e.detail.value});},onContact:function(e){this.setData({contact:e.detail.value});},submit:function(){var d=this.data;if(!d.content){wx.showToast({title:'请填写内容',icon:'none'});return;}api.submitFeedback({content:d.content,contact:d.contact}).then(function(){wx.showToast({title:'感谢反馈!',icon:'success'});setTimeout(function(){wx.navigateBack();},1000);}).catch(function(e){wx.showToast({title:e.message||'提交失败',icon:'none'});});}});""")
W("pages/feedback/feedback.wxml", WXS+"""<view class="page-wrap" style="padding:30rpx;"><view style="background:#fff;border-radius:16rpx;padding:30rpx;"><view style="font-size:28rpx;font-weight:bold;margin-bottom:20rpx;">意见反馈</view><textarea placeholder="请描述您遇到的问题或建议" value="{{content}}" bindinput="onContent" style="width:100%;height:240rpx;border:1rpx solid #f0f0f0;border-radius:8rpx;padding:16rpx;font-size:26rpx;"/><input placeholder="联系方式（选填）" value="{{contact}}" bindinput="onContact" style="height:80rpx;border-bottom:1rpx solid #f0f0f0;font-size:26rpx;margin-top:20rpx;"/><button class="btn-primary" bindtap="submit" style="margin-top:30rpx;">提交反馈</button></view></view>""")

print("Done! All 12 pages completed.")
